### ISSUE TITLE
HappyPancake anti-adblock with Adblock Plus & AdBlock

### ISSUE THREAD

**Issue by Antsa92** [finnish-easylist-addition/finnish-easylist-addition#267]
I tested HappyPancake with Adblock Plus & AdBlock and having same problem like what was on with uBlock. uBlock fixed but can fix also with Adblock Plus users? After sending message it say have Adblock on and need disable to send message.

**Comment by peace2000** [comment]
Finnish Easylist is pending to be part of ABP's default subscriptions. If there are any anti adblock entries for ABP, they won't accept this list as a part of their default lists. I guess they are afraid of legal challenges but I'mt not completely sure.

If The Finnish Easylist isn't part of ABP's default lists, many will be completely without it because most of people don't realize there is a Finnish list available but you just have find it and add it manually.

**Comment by peace2000** [comment]
And I highly suspect that Adblock (not plus version) has similar policies though I cannot verify it. I have sent them also a request to add the Finnish list to their default lists but still waiting for that.
