### ISSUE TITLE
seiska.fi

### ISSUE THREAD

**Issue by DandelionSprout** [finnish-easylist-addition/finnish-easylist-addition#273]
### List the website(s) you're having issues:

`https://www.seiska.fi/`

### What happens?

Placeholder carousel thing partway down the page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/118909110-d0eaaf80-b922-11eb-881c-7739a8ca2b0a.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 90.0.4430.212 x64
- Adblock Extension/version: uBO 1.35.3b5 + IDCAC 3.3.0

### Other details:

I propose `seiska.fi##div[class*=AdAndCarousel__Wrapper]`

Additionally, the "Suosituimmat" section on the right fails to load, for reasons I'm not certain about.

![image](https://user-images.githubusercontent.com/22780683/118908906-8406d900-b922-11eb-888a-947bdfa76978.png)

**Comment by peace2000** [comment]
Added a blocking rule for that empty element.

The issue with Suosituimmat ("Most popular") category is caused by not accepting cookies. So only those who use annoyance lists to block cookie banners, suffer this issue.

As a annoyance list user by myself too, I think that a cookie banner in the middle of the page is more annoying than a non-relevant category that won't load. That's why I would leave it that way in this case. Annoyance lists are not enabled by default anyway so people who use them probably know the risks behind them.
