### ISSUE TITLE
kotiliesi.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#285]
### List the website(s) you're having issues:

`https://kotiliesi.fi/`

### What happens?

Ad placeholders.

![image](https://user-images.githubusercontent.com/84513173/121015355-95196c00-c7a3-11eb-83f6-dbef77013966.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/84513173/118984355-18565780-b986-11eb-82e2-24e68fe6d2c9.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Firefox 89.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.35.2

### Other details:
This removes "Kaupalliset yhteistyöt": `kotiliesi.fi##.widget_google-ad-manager` 

There are also a lot of other placeholders (pink box with the text "kotiliesi" inside it) all around the site that are all meant for ads, but I wasn't sure if all of those should be removed since it moves stuff around? Doesn't really break any functionality, but can make layout look weird.

Those can be removed with: `kotiliesi.fi##.placeholder`

**Comment by peace2000** [comment]
Fixed. I added that placeholder removing rule for subpages but I skipped the main page because it would indeed look kinda stupid.

Here's a sample subpage: https://kotiliesi.fi/kategoria/ihmiset-ja-ilmiot/

You can reveal more articles by clicking "Katso lisää artikkeleita" which, in my opinion "fixes" the issue that there are 2 empty placeholders at the end.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/7c571a78885d6fa257243804a63ab45d3e6c5959

**Comment by Nojuuu** [comment]
@peace2000 I checked the site on a mobile device and there I think all placeholders can be removed because everything there seems to be using a column layout.

**Comment by peace2000** [comment]
On mobile device hiding that element looks good but not on desktop.

So I added a rule to block that element on the main page only if a mobile device is being used.

```
!#if env_mobile
kotiliesi.fi##.placeholder
!#endif
```

@Nojuuu
