### ISSUE TITLE
Note to myself: endless loading, Elisa.fi

### ISSUE THREAD

**Issue by peace2000** [finnish-easylist-addition/finnish-easylist-addition#336]
https://elisa.fi/kauppa/puhelinliittymat

**Comment by Nojuuu** [comment]
`@@||inpref.s3.amazonaws.com/frosmo.easy.js$script,domain=elisa.fi`, I think that fixes it?

**Comment by peace2000** [comment]
Yeah that's good.

https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/77beaa6ce5a8d99f28ba919c1eb7062acce72501

**Comment by Nojuuu** [comment]
I was getting infinite load yesterday also because of my own filters were removing parameters from googletagmanager. So maybe it could be related to that, does allowing `@@||www.googletagmanager.com/gtag/js?id=G-E52CJ7JS9Z&l=dataLayer&cx=c$script,domain=elisa.fi` help? That's blocked by Lowe's list.

**Comment by peace2000** [comment]
No it doesn't, even if I disable uBO I can occasionally see this issue again when i refresh the page many times enough, bypassing browser's cache.

**Comment by Nojuuu** [comment]
Yeah, I get it now too with everything disabled.

**Comment by Nojuuu** [comment]
It also doesn't matter which browser you use. So the problem is probably on their side.

**Comment by peace2000** [comment]
Ok yeah so this seems to be just a site issue after all... Thanks for confirming.
