### ISSUE TITLE
nettivuokraus.com

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#397]
### List the website(s) you're having issues:

```
https://www.nettivuokraus.com/vuokrataan/ajoneuvot-ja-tarvikkeet/autonvuokraus/henkiloauto/
```

### What happens?

`nettivuokraus.com##.listing:not(.tricky_link_listing)` hides  results

![image](https://user-images.githubusercontent.com/84513173/148462951-1953deb5-9b83-46db-85b0-bd0c130bffc1.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.2

</details>

### Other details:

```

```

**Comment by peace2000** [comment]
Changed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c36b6e1c7fff3cbbe2ef4ab975f4c4206e090050

Some netti-domains have ads which that rule targets e.g.: https://www.nettikone.com/myydaan?id_country[]=73 which is why I'll keep the rule but change it instead of removing.
