### ISSUE TITLE
s-pankki.fi (an account required)

### ISSUE THREAD

**Issue by 07416** [finnish-easylist-addition/finnish-easylist-addition#405]
### List the website(s) you're having issues:
`https://online.s-pankki.fi/` (requires logging in)

### What happens?

There's a marked ad (`Mainos`) on the online banking frontpage (`Etusivu`). 

May be dynamic, doesn't appear when I signed in later with Chromium (no addons).

### List Subscriptions you're using:

uBlock Origin's global defaults and this list.

### Other details:

suggested filter: `##.c_card-cms-box:has-text(Mainos)` (`.c_card-cms-box` matches all three elements, with the orange outline)

The ad element (`Mainos`) is on the bottom.

![image](https://user-images.githubusercontent.com/14923168/158600593-e29b3ea2-6845-4225-8c8e-055ec081c0d9.png)

**Comment by peace2000** [comment]
@Nojuuu Is it possible for you to check this?

**Comment by Nojuuu** [comment]
Unfortunately I don't use S-Pankki.

**Comment by peace2000** [comment]
I might to check this after a week.

**Comment by peace2000** [comment]
Well.. The last box says that it's an ad, but the second box doesn't have that text. So, in some way S-pankki makes a difference between the second and the last box. That's why I would consider the second box self-promo but the last as ad.

Have been too busy to check this, I do have S-pankki account but haven't used it for a long time because I mainly use another bank so I don't remember my account credentials.. I'll renew them but it goes to the next week (this time I really mean next week :D).

**Comment by peace2000** [comment]
I thought that by visiting a local customer service point I would get new credentials asap but they said that they'll send them via mail but it takes about one week... :D :D

Well, but at least this is in progress... :D

**Comment by 07416** [comment]
The ads appear to have been removed at some point, I certainly haven't seen any in a while (currently no cosmetic filters run on the page on my system).
