### ISSUE TITLE
hinta.fi

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#414]
Maybe these should be more specific, if possible?
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/289596d7a9df85d9575a2ce5ef5610ed988eb069/Finland_adb.txt#L1298-L1300

**Comment by peace2000** [comment]
I think this is reasonable: https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/b23de08734af355a5d0d0f188e4da066fb71ab76

I removed cdon related because it seems cdon is not listed in hinta.fi anymore.

You can test opening dna.fi product links through this: https://hinta.fi/3377831/oneplus-10-pro

![kuva](https://user-images.githubusercontent.com/17256841/182039989-7a770d21-1004-4af4-9171-6810b334b3f4.png)

**Comment by Nojuuu** [comment]
Yep, seems to still work 👍
